config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'ideas#index'
  get 'term_of_service', to: 'tos#index'
  get 'policy', to: 'policy#index'
  namespace :ideas do
    resources :solved, only: %i[update destroy]
  end
  resources :ideas, only: %i[show new create edit update destroy] do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :ideas, only: %i[index show create]
      resources :likes, only: %i[show create destroy]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/idea.rb
# frozen_string_literal: true

class Idea < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy

  validates :title, presence: true
  validates :elevatorpitch, presence: true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ideas, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :email, length: { maximum: 50 }, presence: true
end

app/controllers/api/v1/idea_controllor.rb
# frozen_string_literal: true

module Api
  module V1
    class IdeasController < ApplicationController
      before_action :set_idea, only: %i[show]

      def index
        @ideas =
          if params[:solved] == 'false'
            Idea.all.where(solved: false).order(created_at: 'DESC')
          else
            Idea.all.where(solved: true).order(created_at: 'DESC')
          end
      end

      def show; end

      private

      def set_idea
        @idea = Idea.find(params[:id])
      end
    end
  end
end

app/controllers/api/v1/ideas_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class IdeasController < ApplicationController
      before_action :authenticate_user!, only: %i[create]

      def index
        @ideas =
          if params[:solved] == 'false'
            Idea.all.where(solved: false).order(created_at: 'DESC')
          else
            Idea.all.where(solved: true).order(created_at: 'DESC')
          end
      end

      def create
        title = params[:title]
        elevatorpitch = params[:elevatorpitch]
        @idea = current_user.ideas.new(title: title, elevatorpitch: elevatorpitch)
        @idea.save!
        render json: { idea: @idea }
      end
    end
  end
end

app/controllers/api/v1/likes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class LikesController < ApplicationController
      before_action :set_idea, only: %i[show]
      before_action :authenticate_user!, only: %i[show create destroy]

      def show
        like = Like.where(
          user: current_user,
          idea: @idea
        )

        render json: {
          like: like,
          totalLike: @idea.likes.length
        }, status: :ok
      end

      def create
        like = current_user.likes.create!(idea_params)
        idea = Idea.find(params[:like][:idea_id])
        render json: {
          like: like,
          totalLike: idea.likes.length
        }
      end

      def destroy
        Like.find(params[:id]).destroy
        head :no_content
      end

      private

      def set_idea
        @idea = Idea.find(params[:id])
      end

      def idea_params
        params.require(:like).permit(:idea_id)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[email name password password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_idea, only: %i[create]

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to idea_path(id: @idea.id)
    else
      @error_comment = @comment
      render template: 'ideas/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_back(fallback_location: root_path, notice: 'コメントを削除しました')
    else
      flash.now[:alert] = 'コメント削除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_idea
    @idea = Idea.find(params[:idea_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :idea_id)
  end
end

app/controllers/ideas/solved_controller.rb
# frozen_string_literal: true

class Ideas::SolvedController < ApplicationController
  before_action :set_idea, only: %i[update destroy]
  before_action :authenticate_user!, only: %i[update destroy]

  def update
    if @idea.update(solved: true)
      redirect_to idea_path(id: @idea.id), notice: 'サービス案を「解決済」に分類しました。'
    else
      redirect_to idea_path(id: @idea.id), alert: 'サービス案を「解決済」に分類することに失敗しました。'
    end
  end

  def destroy
    if @idea.update(solved: false)
      redirect_to idea_path(id: @idea.id), notice: 'サービス案を「未解決」に分類しました。'
    else
      redirect_to idea_path(id: @idea.id), alert: 'サービス案を「未解決」に分類することに失敗しました。。'
    end
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/ideas/solveds_controller.rb
# frozen_string_literal: true

class Ideas::SolvedsController < ApplicationController
  before_action :set_idea, only: %i[update destroy]
  before_action :authenticate_user!, only: %i[update destroy]

  def update
    @idea.update(solved: true)
    redirect_to idea_path(id: @idea.id), notice: 'サービス案を「解決済」に分類しました。'
  end

  def destroy
    @idea.update(solved: false)
    redirect_to idea_path(id: @idea.id), notice: 'サービス案を「未解決」に分類しました。'
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/ideas_controller.rb
# frozen_string_literal: true

class IdeasController < ApplicationController
  before_action :set_idea, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @ideas = Idea.all
  end

  def show
    @comments = @idea.comments
    @comment = current_user.comments.new if user_signed_in?
  end

  def new; end

  def edit
    if current_user.admin || @idea.user == current_user
      render 'edit'
    else
      redirect_to root_path
    end
  end

  def update
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'サービス案を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to root_path, notice: '投稿されたサービス案を削除しました。'
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :elevatorpitch)
  end
end

app/controllers/policy_controller.rb
# frozen_string_literal: true

class PolicyController < ApplicationController
end

app/controllers/tos_controller.rb
# frozen_string_literal: true

class TosController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def default_meta_tags
    {
      reverse: true,
      charset: 'utf-8',
      separator: '|',
      description: 'Web開発者を対象としたWebサービスアイデア投稿・閲覧サービス',
      canonical: 'https://idearu.herokuapp.com/',
      icon: [
        { href: image_url('favicon.png') }
      ],
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: 'https://idearu.herokuapp.com/',
        image: image_url('logo.png')
      }
    }
  end
end

app/views/ideas/edit.html.slim
- content_for(:html_title) { 'アイデア編集' }
.edit_container.container.my-3
  .box
    = render(partial: 'layouts/errors_form',  locals: { model: @idea })
    = form_with(model: @idea, local: true, class: "form__main") do |form|
      .form__items
        .field.form__item
          = form.label :title, class: "label"
          .control
            = form.text_field :title, value: @idea.title, class: "input"
        .field.form__item
          = form.label :elevatorpitch, class: "label"
          .control
            = form.text_area :elevatorpitch, value: @idea.elevatorpitch, class: "textarea", rows: "10"
        .actions.form__action.has-text-centered
          = form.submit '内容変更', class: "button is-success"

app/views/ideas/index.html.slim
.usage-container.has-background-black-ter
  .container
    .usage-body
      h1.usage-title.title.has-text-white.has-text-centered.is-size-1-tablet.is-size-3-mobile
        | エレベーター<br class='is-hidden-tablet'>ピッチ形式で<br>Webサービスの<br class='is-hidden-tablet'>アイデアを投稿
      .features
        h2.features__title.mb-4.has-text-centered.has-text-white
          | ログインすると以下のことができます。
        .features__items
          .features__item
            .features__item-inner
              .features__item-icon
                i.far.fa-lightbulb.fa-lg
              .features__item-label
                | 投稿
          .features__item
            .features__item-inner
              .features__item-icon
                i.far.fa-thumbs-up.fa-lg
              .features__item-label
                | いいね
          .features__item
            .features__item-inner
              .features__item-icon
                i.far.fa-comment.fa-lg
              .features__item-label
                | コメント
        .features__actions.mt-5
          .features__action
            = link_to new_user_registration_path, class: 'button is-warning is-medium is-fullwidth has-text-black' do
              | アカウント登録

= react_component("ideas")

app/views/ideas/new.html.slim
- content_for(:html_title) { '新規投稿' }
= react_component("ideasNew")

app/views/ideas/show.html.slim
- content_for(:html_title) { @idea.title }
.main
  header.main__header
    .container.is-max.has-padding
      h1.title.is-4
        = @idea.title
        | を解決したい
  .main__body
    .idea-container.container.has-padding
      .idea-wrapper.box
        header.idea-header.pb-2
          .user__items.is-flex.is-justify-content-space-between
            .user__item.is-size-6
              | 投稿者:
              <br class='is-hidden-tablet'>
              = @idea.user.name
            .user__item.is-size-6
              | 投稿日時:
              <br class='is-hidden-tablet'>
              = l @idea.created_at
        .idea-elevatorpitch.pt-4.is-size-5
          = @idea.elevatorpitch
        - if user_signed_in?
          .idea__items
            .idea__item
              = react_component("like", ideaId: @idea.id)
            .idea__item.comment__length
              <i class="far fa-comment fa-fw fa-lg "></i>
              = @idea.comments.length
            - if current_user.id == @idea.user.id || current_user.admin
              = link_to('編集', edit_idea_path(@idea) , class: "idea__item column has-text-grey")
              = link_to('削除', @idea, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "idea__item column has-text-danger", id: "idea_delete")
        - if user_signed_in? && current_user.admin?
          .switch-solved
            - if @idea.solved
              = link_to('未解決にする', ideas_solved_path(@idea), method: :delete, class: "button is-primary")
            - else
              = link_to('解決済みにする', ideas_solved_path(@idea), method: :patch, class: "button is-danger")
      .comments-container
        .comments-title.has-text-weight-bold.my-2
          | コメント
        - @idea.comments.each do |comment|
          .comment-container.card.media.p-4
            .comment__user-container.media-content
              .comment__title.content.pb-2
                .comment__user-name
                  = comment.user.name
                .comment__created
                  = l comment.created_at
                  br
              .comment__description.pb-5
                = comment.content
              - if user_signed_in?
                -if comment.user_id == current_user.id || current_user.admin?
                  .comment__destroy-link.pt-3.has-text-right
                    = link_to('削除', idea_comment_path(@idea, comment), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "has-text-danger", id: "comment_delete")
        - if user_signed_in?
          = form_with(model: [@idea, @comment], class: "comment-form__main my-4") do |form|
            = render(partial: 'layouts/errors_form',  locals: { model: @comment })
            .comment-form__items
              .field.comment-form__item
                .control
                  = form.text_area :content, class: "textarea"
                  = form.hidden_field :idea_id, value: @idea.id
              .field.comment-form__action.actions
                = form.submit "コメントする", class: "button is-info is-normal"
        - else
          p.has-text-centered.my-3 コメントするにはログインが必要です。

app/views/layouts/_errors_form.html.slim
- if model.errors.any?
  .alert
    ul.alert__items
      - model.errors.full_messages.each do |message|
        li type="disc" class="alert__item has-text-danger ml-5"
          = message

app/views/layouts/_footer.html.slim
footer.footer.has-background-white.py-6
  .footer__content.content.has-text-centered
    p.footer__content-top-items
      strong.is-size-7
        a.footer__content-top-item.mx-3 href="/term_of_service"
          | 利用規約
        a.footer__content--top-item.mx-3 href="/policy"
          | プライバシーポリシー
    p.footer__content-bottom-items.is-size-7
      strong.footer__content-bottom-item
        | ©️ 2021 alto-I

app/views/layouts/_header.html.slim
= react_component('header', isUserSignedIn: user_signed_in?)

app/views/layouts/application.html.slim
doctype html
html
  title
      = content_for?(:html_title) ? yield(:html_title) + " | Idearu" : "Idearu"
  head
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = display_meta_tags default_meta_tags
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"
  body
    .wrapper
      .wrapper__start
        = render 'layouts/header'
        - if notice.present?
          .notice.has-background-success
            .container.is-max.has-padding
              p.has-text-white-ter.has-text-centered
                = notice
        - if alert.present?
          .alert.has-background-danger
            p.has-text-white-ter.has-text-centered
              = alert
        = yield
      .wrapper__end
        = render 'layouts/footer'

app/views/policy/index.html.slim
- content_for(:html_title) { 'プライバシーポリシー' }
.container.section
  h1.title.is-3
    | プライバシーポリシー
  p.mb-3
    | idearu（以下，「当サイト」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
  h2.is-size-5
    | 第1条（個人情報）
  p.ml-1.my-3
    | 「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
  h2.is-size-5
    | 第2条（個人情報の収集方法）
  p.ml-1.my-3
    | 当サイトは，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当サイトの提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。
  h2.is-size-5
    | 第3条（個人情報を収集・利用する目的）
  p.ml-1.my-3
    | 当サイトが個人情報を収集・利用する目的は，以下のとおりです。
  ol.ml-5.my-3
    li
      | 当サイトサービスの提供・運営のため
    li
      | ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
    li
      | ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当サイトが提供する他のサービスの案内のメールを送付するため
    li
      | メンテナンス，重要なお知らせなど必要に応じたご連絡のため
    li
      | 利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
    li
      | ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
    li
      | 有料サービスにおいて，ユーザーに利用料金を請求するため
    li
      | 上記の利用目的に付随する目的
  h2.is-size-5
    | 第4条（利用目的の変更）
  ol.ml-5.my-3
    li
      | 当サイトは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
    li
      | 利用目的の変更を行った場合には，変更後の目的について，当サイト所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。
  h2.is-size-5
    | 第5条（個人情報の第三者提供）
  ol.ml-5.my-3
    li
      | 当サイトは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
      ol.ml-5.my-3
        li
          | 人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
        li
          | 公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
        li
          | 国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
        li
          | 予め次の事項を告知あるいは公表し，かつ当サイトが個人情報保護委員会に届出をしたとき
          ol.ml-5.my-3
            li
              | 利用目的に第三者への提供を含むこと
            li
              | 第三者に提供されるデータの項目
            li
              | 第三者への提供の手段または方法
            li
              | 本人の求めに応じて個人情報の第三者への提供を停止すること
            li
              | 本人の求めを受け付ける方法
    li
      | 前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
      ol.ml-5.my-3
        li
          | 当サイトが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
        li
          | 合併その他の事由による事業の承継に伴って個人情報が提供される場合
        li
          | 個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合
  h2.is-size-5
    | 第6条（個人情報の開示）
  ol.ml-5.my-3
    li
      | 当サイトは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。
      ol.ml-5.my-3
        li
          | 本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合
        li
          | 当サイトの業務の適正な実施に著しい支障を及ぼすおそれがある場合
        li
          | その他法令に違反することとなる場合
    li
      | 前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。
  h2.is-size-5
    | 第7条（個人情報の訂正および削除）
  ol.ml-5.my-3
    li
      | ユーザーは，当サイトの保有する自己の個人情報が誤った情報である場合には，当サイトが定める手続きにより，当サイトに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
    li
      | 当サイトは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
    li
      | 当サイトは，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。
  h2.is-size-5
    | 第8条（個人情報の利用停止等）
  ol.ml-5.my-3
    li
      | 当サイトは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
    li
      | 前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
    li
      | 当サイトは，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
    li
      | 前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
  h2.is-size-5
    | 第9条（プライバシーポリシーの変更）
  ol.ml-5.my-3
    li
      | 本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
    li
      | 当サイトが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
  h2.is-size-5
    | 第10条（お問い合わせ窓口）
  p.ml-1.my-3
    | 本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。
  p.ml-1.my-3
    |  Eメールアドレス： blmalidy@gmail.com
  p.has-text-right
    | 以上